[package]
name = "ma_time"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
quanta.workspace = true
once_cell.workspace = true
serde.workspace = true
web-time.workspace = true
